// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnhFFHbfGdM6vZ1ox3SyCZc73zwb2QIvQ',
    appId: '1:444565550302:web:0aa2bbd9fc41db64cafe4f',
    messagingSenderId: '444565550302',
    projectId: 'quero-doce-d5f27',
    authDomain: 'quero-doce-d5f27.firebaseapp.com',
    storageBucket: 'quero-doce-d5f27.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu2Y-ZTjCa95TnWfLkTHBFPOKgNd3VLXY',
    appId: '1:444565550302:android:c264ad11896674fecafe4f',
    messagingSenderId: '444565550302',
    projectId: 'quero-doce-d5f27',
    storageBucket: 'quero-doce-d5f27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFcpD_mwGBBOpmsZZKVEEt9Yu5ZWcut7E',
    appId: '1:444565550302:ios:8816dd015c5bccd6cafe4f',
    messagingSenderId: '444565550302',
    projectId: 'quero-doce-d5f27',
    storageBucket: 'quero-doce-d5f27.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFcpD_mwGBBOpmsZZKVEEt9Yu5ZWcut7E',
    appId: '1:444565550302:ios:8816dd015c5bccd6cafe4f',
    messagingSenderId: '444565550302',
    projectId: 'quero-doce-d5f27',
    storageBucket: 'quero-doce-d5f27.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnhFFHbfGdM6vZ1ox3SyCZc73zwb2QIvQ',
    appId: '1:444565550302:web:28c291eb0fc24c51cafe4f',
    messagingSenderId: '444565550302',
    projectId: 'quero-doce-d5f27',
    authDomain: 'quero-doce-d5f27.firebaseapp.com',
    storageBucket: 'quero-doce-d5f27.firebasestorage.app',
  );
}
